include/realtime_tools/realtime_box.h
=> RealtimeBox: Fix member doc

include/realtime_tools/realtime_server_goal_handle.h
This PR is rerouting changes of #18 to `kinetic-devel`
=> Add feedback sending capability to RealtimeServerGoalHandle --KINETIC reroute

include/realtime_tools/realtime_server_goal_handle.h
addresses https://github.com/ros-controls/ros_controllers/issues/352
=> remove duplicated action pointer types  from RealtimeServerGoalHandle

include/realtime_tools/realtime_box.h, include/realtime_tools/realtime_server_goal_handle.h
This PR removes a couple includes in header files that weren't being used.
=> Remove Unused Includes

.travis.yml
See also ros-controls/ros_control#440
=> Migrate to new industrial_ci

test/realtime_server_goal_handle_tests.cpp
=> avoid deprecations

.travis.yml, include/realtime_tools/realtime_buffer.h, src/realtime_clock.cpp
based on top of #62 
Fixes the msbuild warnings shown here: https://ci.ros2.org/job/ci_windows/11050/msbuild/new/fileName.1901396525/
```
discarding return value of function with 'nodiscard' attribute
```
=> Fix msbuild warning

.travis.yml, include/realtime_tools/realtime_buffer.h
=> Made copy-constructor const

include/realtime_tools/realtime_buffer.h
This will resolve issue https://github.com/ros-controls/ros2_controllers/issues/247
=> Adding new reset() function for Issue-247.

.github/workflows/ci-format.yml
The equivalent of https://github.com/ros-controls/ros2_control/pull/887
=> Bump version formatting action versions

CMakeLists.txt, package.xml
This is related to:
- https://github.com/ros-controls/kinematics_interface/pull/13
- https://github.com/ros-controls/ros2_control/pull/926
- https://github.com/ros-controls/ros2_controllers/pull/510
Here are the colcon docs on overriding: https://colcon.readthedocs.io/en/released/user/overriding-packages.html#how-to-make-it-easier-for-your-users-to-override
Here is the ament_cmake user guide: https://docs.ros.org/en/rolling/How-To-Guides/Ament-CMake-Documentation.html
=> Fix overriding of install

.github/workflows/ci-ros-lint.yml
As in the other repos, e.g. https://github.com/ros-controls/ros2_control/pull/1092/files
=> Update CI lint job

.github/workflows/humble-rhel-binary-build.yml, .github/workflows/iron-rhel-binary-build.yml, .github/workflows/rolling-rhel-binary-build.yml
Workflows had invalid syntax, e.g., see this one
https://github.com/ros-controls/realtime_tools/actions/runs/7618397885/workflow
=> Fix RHEL workflows

CMakeLists.txt, src/thread_priority.cpp
=> Add fixes to the code to work for the windows systems

include/realtime_tools/thread_priority.hpp
Adding #pragma message for Windows Systems
=> Removing thread_priority.hpp warning for Windows Systems

CMakeLists.txt, include/realtime_tools/realtime_helpers.hpp, src/realtime_helpers.cpp, test/thread_priority_tests.cpp
This PR uses the commits from PR: #140 and add more fixes on top of it and some refactoring and renaming of methods
Closes  #140
=> Add methods to set the thread affinity

include/realtime_tools/async_function_handler.hpp
This would be needed for the statistics of the controllers and the hardware components
=> Add method to get the current callback time and period

.github/workflows/README.md, .github/workflows/abi-compatibility.yml, .github/workflows/binary-build.yml, .github/workflows/ci-pre-commit.yml, .github/workflows/debian-build.yml, .github/workflows/rhel-semi-binary-build.yml, .github/workflows/source-build.yml, README.md
Due after the next patch release on November 15th.
=> Remove iron workflows and update readme

include/realtime_tools/realtime_buffer.hpp, include/realtime_tools/realtime_clock.hpp
=> Remove wrong comments

.github/workflows/jazzy-binary-build-win.yml, .github/workflows/rolling-binary-build-win.yml
=> Install boost on jazzy as well

include/realtime_tools/realtime_publisher.hpp
I looked into RTPublisher code for https://github.com/ros-controls/ros2_controllers/pull/1586. I made some changes to help myself. I'm making this PR just in case this is useful to others.
=> Update the docstring for realtime_publisher.hpp

realtime_tools/CMakeLists.txt
Fixes https://github.com/ros-controls/realtime_tools/actions/runs/15183848880/job/42699560392?pr=334
closes: #335
=> export Boost dependency

.github/workflows/rolling-compatibility-build.yml
to check if rolling is building on older distros
=> Add compatibility build workflow

.github/workflows/jazzy-check-docs.yml, .github/workflows/rolling-check-docs.yml
https://github.com/ros-controls/control.ros.org/pull/470
=> Add CI job for docs

realtime_tools/include/realtime_tools/realtime_thread_safe_box.hpp
Earlier, something like this was accepted
`rt_active_goal_.set([](auto goal) { goal = RealtimeGoalHandlePtr(); });`
Note the call-by-value, it won't change the internal value of the box, without any notice. Took me some time to debug the client code.
=> Only accept callable with T&

realtime_tools/doc/realtime_publisher.rst
Fixes https://github.com/ros-controls/realtime_tools/issues/375
=> Fix the realtime publisher doc

.github/workflows/humble-source-build.yml, .github/workflows/jazzy-source-build.yml, .github/workflows/rolling-source-build.yml
https://github.com/ros-controls/control_toolbox/pull/478
=> Fix source builds
