.travis.yml
This adds support for lunar
supersedes #8
=> switch to industrial_ci

include/realtime_tools/realtime_server_goal_handle.h
With the proposed changes, the real time goal handle allows for a cancel request to happen and the action to be terminated at a later time from within the real time thread.
=> Updated RT goal handle to handle cancel requests

.travis.yml, include/realtime_tools/realtime_publisher.h
`RealtimePublisherSharedPtr` is to be used in `ros_controllers` to replace some looong `boost::shared_ptr` declarations and typedef..
=> C++11 and melodic travis updates

include/realtime_tools/realtime_buffer.h
The copy constructor on the realtime buffer doesn't follow the standard copy-constructor format of pass-by-const-reference, but rather uses pass-by-reference. There is no reason for this, it should be const to be const-correct and follow standard copy-constructor idioms. This change also will allow RealtimeBuffer to be an STL container element.
I've opened this PR against `melodic-devel`, but the file `realtime_buffer.h` is identical between kinetic and melodic so ideally I would like to see this change cherry picked backward to at least `kinetic-devel`.
=> Made RealtimeBuffer's copy-constructor const

include/realtime_tools/realtime_buffer.h, include/realtime_tools/realtime_publisher.h, src/realtime_clock.cpp
`usleep` is not available on Windows, replace it with `this_thread::sleep_for` (available since c++11)
also a minor indentation update in include/realtime_tools/realtime_publisher.h, converted existing tabs to spaces
=> use this_thread::sleep_for on Windows

CMakeLists.txt, package.xml
~~Please review #37 first. I'll rebase this once #37 is through the review processes. The only file changed by this PR is `package.xml`~~ Edit: Changed my mind, it looks like this can go in without creating a merge conflict with #37 so this PR is ready to be reviewed
This PR
* Updates the `package.xml` to use format 2
* Adds a `<build_export_depend>` for `actionlib` since its headers are included by headers installed by this package
* Shortens the package.xml description since it appeared to be out of date
This is a step towards #35
=> Package format 2

CMakeLists.txt, include/realtime_tools/realtime_publisher.h, package.xml, test/realtime_box_tests.cpp, test/realtime_buffer_tests.cpp, test/realtime_clock_tests.cpp, test/realtime_publisher.test, test/realtime_publisher_tests.cpp, test/realtime_server_goal_handle.test, test/realtime_server_goal_handle_tests.cpp
This PR adds unit tests to make sure stuff doesn't get broken while porting to ROS 2 (#35). Also included is a fix for a race condition where `RealtimePublisher` may not publish the first message. The unit test needs this fix to pass reliably.
`RealtimePublisher` initialized `turn_` with `REALTIME`, and `publishingLoop()` also sets `turn_` to `REALTIME`. If `unblockAndPublish()` is called before before the publishing thread gets scheduled then the first message won't be published because `turn_` is overwritten. This fixes the issue by initializing `turn_` to a new state `LOOP_NOT_STARTED`. This prevents `trylock()` from returning `true` because the state is not `REALTIME`, which means there is no message to get lost.
=> Add unit tests + fix publisher bug

CMakeLists.txt, include/realtime_tools/realtime_box.h, include/realtime_tools/realtime_buffer.h, include/realtime_tools/realtime_clock.h, include/realtime_tools/realtime_publisher.h, include/realtime_tools/realtime_server_goal_handle.h, src/realtime_clock.cpp, test/realtime_server_goal_handle_tests.cpp
This removes all uses of boost. This PR depends on #37. I'll rebase this one once that's through the review process.
This change probably breaks ABI (changes the size of `RealtimeClock`), so it should be targeted at a `noetic-devel` branch.
This is a step towards #35
=> Remove boost

CMakeLists.txt, include/realtime_tools/realtime_server_goal_handle.h
Follow up from #39. This removes actionlib typedefs. It should be merged after ros/actionlib#145 is released into melodic.
=> Remove actionlib definitions

CMakeLists.txt
There is a typo that adds the `actionlib` include directories to the wrong test target. I noticed this while building `realtime_tools` on Buster using `noetic` upstream dependencies, but I don't know why this hasn't showed up before.
Without this PR I see
```
In file included from /home/sloretz/rtt/src/realtime_tools/test/realtime_server_goal_handle_tests.cpp:31:
/home/sloretz/rtt/src/realtime_tools/include/realtime_tools/realtime_server_goal_handle.h:37:10: fatal error: actionlib/server/action_server.h: No such file or directory
#include <actionlib/server/action_server.h>
```
Building using command:
```
catkin_make_isolated --catkin-make-args all tests VERBOSE=1 --cmake-args -DBUILD_TESTING=1 -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCMAKE_BUILD_TYPE=Release
```
=> realtime_server_goal_handle_tests needs actionlib

include/realtime_tools/realtime_publisher.h
Current when `RealtimePublisher` is constructed with default constructor and `init` function is never called, joining an "empty" thread will cause exception. 
This PR checks whether the thread is joinable before joining.
=> Check whether thread joinable before joining

include/realtime_tools/realtime_publisher.h
Use `std::atomic` types for safely accessing variables from different threads.
=> Use atomic types

include/realtime_tools/realtime_publisher.h
C++11 has `std::atomic` for atomic variable. This PR uses it instead of classical `volatile` variable.
=> Use std::atomic instead of volatile

include/realtime_tools/realtime_server_goal_handle.h
Some fixes to get ros2_controller's PR#26 working. I'm using createWallTimer to run the runNonRealtime() function at a rate 20Hz, and calling setFeedback sometimes makes these threads hit race conditions. 
Besides that the action server does not appreciate success/cancel/abort being sent multiple times; it issues a warning. This is also addressed by setting the booleans to false once sent.
Downstream PR: https://github.com/ros-controls/ros2_controllers/pull/26
=> Realtime server goal thread handle safety + additional warning fixes (#2)

include/realtime_tools/realtime_publisher.h
Follow-up on #52.
Adds missing `#include  <atomic>`, and alpha-sorts the includes.
=> Add missing #include <atomic>

include/realtime_tools/realtime_server_goal_handle.h
This pull request is attempting to fix the CI failure seen here https://github.com/ros-controls/control_toolbox/pull/103.
```
2021-01-04T20:36:46.7269161Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/test/realtime_server_goal_handle_tests.cpp:39:
2021-01-04T20:36:46.7271407Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_server_goal_handle.h: In member function ‘void realtime_tools::RealtimeServerGoalHandle<Action>::runNonRealtime()’:
2021-01-04T20:36:46.7274284Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_server_goal_handle.h:167:7: error: cannot convert ‘const string {aka const std::__cxx11::basic_string<char>}’ …
```
=> Fix the mis-type error in realtime_server_goal_handle.h

include/realtime_tools/realtime_clock.h, src/realtime_clock.cpp
Since https://github.com/ros2/rclcpp/pull/1432 (upcoming in Galactic), we should not initialize with a single integer
as the units are ambiguous.
---
I wasn't sure if I should target `foxy-devel` or the `ros2_devel` branch. I picked `foxy-devel` since it seems the most up-to-date. This fix is compatible with Foxy.
=> Fix deprecation warnings when constructing rclcpp::Duration

include/realtime_tools/realtime_server_goal_handle.h
Fix a compile-time issue with the latest ROS 2 code.
Signed-off-by: Michael Jeronimo <michael.jeronimo@openrobotics.org>
=> Accommodate the RCLCPP_WARN macro by using a C string

CMakeLists.txt, include/realtime_tools/thread_priority.hpp, src/thread_priority.cpp
As suggested in this ros2_control PR:  https://github.com/ros-controls/ros2_control/pull/792
Add a library to detect a realtime kernel and set thread priority. Having it here should make it easy to link against from other packages and generally seems like a better place to have the library than inside `controller_manager`.
=> Add a library to detect a realtime kernel and set thread priority

CMakeLists.txt
This library should be shared so other shared libraries can link it.
I discovered this during this PR:  https://github.com/ros-planning/moveit2/pull/1540
Note that the library I'm linking it to is another shared (aka dynamic) library.
Prior to this PR I get this error:
```
--- stderr: moveit_servo
/usr/bin/ld: /home/andy/ws_ros2/install/realtime_tools/lib/libthread_priority.a(thread_priority.cpp.o): warning: relocation against `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' in read-only section `.text.unlikely'
/usr/bin/ld: /home/andy/ws_ros2/install/realtime_tools/lib/libthread_priority.a(thread_priority.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTTSt14basic_ifstreamIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
```
--- …
=> Make `thread_priority` a shared library

package.xml
This package looks for `ament_cmake_gmock` explicitly for testing - it should declare the dependency.
https://github.com/ros-controls/realtime_tools/blob/0d6b39707ce9b7bc48a2ecbf2086240d9ffd9892/CMakeLists.txt#L26
This should resolve build failures on RHEL: https://build.ros2.org/job/Gbin_rhel_el864__realtime_tools__rhel_8_x86_64__binary/
=> Add missing test dependency on ament_cmake_gmock

.github/workflows/ci-format.yml, .pre-commit-config.yaml
- Use pydocstyle instead of pep257 because it replaces it.
-  Bump versions of hooks.
- Remove fixed python version from formatting action.
- Fix action warnings about Node.js 12 by updating them. 
- Bump version of clang-format.
=> 🔧Fixes and updated on pre-commit hooks and their action.

CONTRIBUTING.md
This fixes a link pointing to broken ros-controls.github.io URLs.
=> Fix links to control.ros.org

test/realtime_clock_tests.cpp
This fixes the issue pointed by @christophfroehlich about the failing tests in the rolling that at the end of the tests upon destruction, the context becomes invalid
```
[ RUN ] RealtimeClock.get_system_time
terminate called after throwing an instance of 'std::runtime_error'
what(): context cannot be slept with because it's invalid
```
=> initialize the global context to avoid runtime_error upon destruction

README.md, codecov.yml
The default branch on codecov is "indigo-devel", I cannot change it: 
> We were unable to update the default branch for this repo
I also fixed the glob for the ignore of the test folder.
=> Fix ignore and patch for codecov

.travis.yml, include/realtime_tools/realtime_buffer.h, include/realtime_tools/realtime_publisher.h, src/realtime_clock.cpp
An update from my previous PR since a lot has been improved since then. This should isolate it to just the fixes to get NON_POLLING to build.
Previously this tried wait on a condition variable using the lock() method as an argument. That didn't build because wait() expects a lock_guard<mutex> rather than a class method. This commit adds a lock_guard as a local var to the publisher loop and uses it to wait when NON_POLLING is defined. 
Additionally, it updates code to call the unlock() method in various places to pick up conditional calls to       the condition var's notify_one() to wake up the cv's wait().
=> Fix building realtime_publisher using NON_POLLING

.github/workflows/ci-coverage-build.yml, .github/workflows/ci-pre-commit.yml, .github/workflows/source-build.yml
Necessary changes to make https://github.com/ros-controls/ros2_control_ci/pull/53 work for noble.
=> [CI] Specify runner/container images

CMakeLists.txt, include/realtime_tools/async_function_handler.hpp, package.xml, test/test_async_function_handler.cpp, test/test_async_function_handler.hpp
The async function handler is moved from https://github.com/ros-controls/ros2_control/pull/1489
=> Add Async Function Handler 

include/realtime_tools/realtime_box_best_effort.h
Since the `RealTimeBoxBestEffort` uses `std::function`s to set and get pointer types (which is great), it should also include `<functional>`.
Note: This doesn't explode in the tests, since there is `gmock` included, which somewhere includes <functional> on the way.
=> Include <functional> in realtime_box_best_effort

CMakeLists.txt, include/realtime_tools/async_function_handler.hpp, include/realtime_tools/realtime_helpers.hpp, include/realtime_tools/thread_priority.hpp, src/realtime_helpers.cpp
Fixes: https://github.com/ros-controls/realtime_tools/issues/177
This is done to also have backward compatibility
=> Rename thread_priority to realtime_helpers header

include/realtime_tools/async_function_handler.hpp
I think this is useful to have more statistical data when we add to the CM
=> [AsyncFunctionHandler] return execution time in nanoseconds

include/realtime_tools/realtime_box_best_effort.h
When users try to include the `realtime_box_best_effort.h` header and build their project with clang the following error will come up (tested on Ubuntu 24.04 and Jazzy):
```
--- stderr: realtime_tools                              
In file included from /usr/local/google/home/lucadv/ws_control/src/realtime_tools/test/realtime_box_best_effort_tests.cpp:32:
/usr/local/google/home/lucadv/ws_control/src/realtime_tools/include/realtime_tools/realtime_box_best_effort.h:74:54: error: use of class template 'std::initializer_list' requires template arguments
74 |     std::enable_if_t<std::is_constructible_v<U, std::initializer_list>>)
|                                                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/initializer_list:45:11: note: template is …
```
=> Fix build error with clang

package.xml
@christophfroehlich reported the missing linking to libcap-dev and later I realised that the dependency is not properly set in the package.xml
https://github.com/ros-controls/control_toolbox/actions/runs/11671849281/job/32499176107
Sorry for the inconvenience
=> Fix libcap-dev dependency

CMakeLists.txt, include/realtime_tools/realtime_helpers.hpp, src/realtime_helpers.cpp, test/realtime_box_best_effort_tests.cpp, test/test_async_function_handler.cpp, test/thread_priority_tests.cpp
Similar to https://github.com/ros-controls/ros2_controllers/pull/961
@firesurfer as we don't have c++20 on humble, we get an error with the designated initializers. 
And I'm not sure about the line 
```c++
std::optional<DefaultConstructable> rt_data_access = box;
```
which gave the error
```
/workspaces/ros2_rolling_ws/src/realtime_tools/test/realtime_box_best_effort_tests.cpp:133:56: error: choosing ‘constexpr std::optional<_Tp>::optional(_Up&&) [with _Up = realtime_tools::RealtimeBoxBestEffort<DefaultConstructable>&; typename std::enable_if<__and_v<std::__not_<std::is_same<std::optional<_Tp>, typename std::remove_cv<typename std::remove_reference<_Tuple>::type>::type> >, std::__not_<std::is_same<std::in_place_t, typename std::remove_cv<typename …
```
=> Add the same compile flags as with ros2_controllers and fix errors

include/realtime_tools/async_function_handler.hpp, include/realtime_tools/realtime_helpers.hpp, src/realtime_helpers.cpp, test/test_async_function_handler.cpp, test/thread_priority_tests.cpp
This PR aims to change the earlier approach with `pthread_setaffinity_np` as it is more generic and it can be scalable to all other controllers. 
The good thing is it doesn't affect the recently merged changes : https://github.com/ros-controls/ros2_control/pull/1852
I've also added corresponding tests in different places
=> Use pthread_setaffinity_np for setting affinity rather than sched_setaffinity

include/realtime_tools/realtime_box.h, include/realtime_tools/realtime_box_best_effort.h, test/realtime_box_tests.cpp
Fixes: https://github.com/ros-controls/realtime_tools/issues/200
@christophfroehlich Thanks for nice summary of the issue.
=> Fix RealtimeBox broken API + `realtime_box_best_effort.h` proper deprecation

.github/workflows/binary-build-win.yml, CMakeLists.txt, test/realtime_box_tests.cpp, test/test_async_function_handler.cpp, test/test_async_function_handler.hpp
The main purpose is to avoid adding code which does not compile on Windows. Github provides windows-2019 runners, which can be used here. However, https://github.com/nektos/gh-act does not support this and I was only to test the workflow online.
- Binary releases are not published for rolling, so I hardcoded jazzy
- I added it now to be triggered at PRs and pushes, but it might be configured to run on comments/labels only.
- Needs https://github.com/ros-controls/ros2_control_ci/pull/175
=> Use windows CI build

include/realtime_tools/realtime_server_goal_handle.hpp
The `state_` field is not used.
=> remove unused state_ field

test/test_async_function_handler.cpp
Fixes https://github.com/ros-controls/realtime_tools/issues/198
I've tested it running it with arg `--retest-until-fail 200`
=> sleep after starting thread to fix flaky tests

include/realtime_tools/realtime_clock.hpp, test/realtime_clock_tests.cpp
See #241: Deprecate it for one release, and then remove the class if no one is raising any concern.
=> Deprecate RealtimeClock class

include/realtime_tools/realtime_helpers.hpp, src/realtime_helpers.cpp
https://github.com/ros-controls/realtime_tools/pull/193 added the inclusion of windows.h in the public header `realtime_helpers.hpp`.
In my limited experience, it is quite important to try to only include windows.h in .cc/.cpp files, as `windows.h` define many problematic macros (`MIN`, `MAX`, `ERROR`) that induce compilation errors when the `realtime_helpers.hpp` header is included before rclcpp or ros_control (as several enums are called `ERROR` in ros_control, see for an example of the confusing errors induced by windows.h https://github.com/ros-controls/gazebo_ros2_control/issues/377 or https://github.com/ros-controls/realtime_tools/pull/204#issuecomment-2498807921, just to mention the most recent I found).
For this reason, I think that in this specific case, even if it may seems not …
=> Avoid to include windows.h in realtime_helpers.hpp

src/realtime_helpers.cpp
These changes allow the detection of realtime kernel even from the `uname` output. It should be more robust.
Fixes: https://github.com/ros-controls/realtime_tools/issues/257
=> Improve has_realtime_kernel method

realtime_tools/include/realtime_tools/realtime_publisher.hpp
Should fix : #24 
Closes: #308 
@bijoua29 can you test this and see if this helps?
=> Fix realtime publisher race condition upon initialization

realtime_tools/include/realtime_tools/realtime_publisher.hpp
Fixes: https://github.com/ros-controls/ros2_controllers/issues/1574
Fixes: https://github.com/ros-controls/ros2_controllers/issues/1669
Apart from this, I've seen a possible vulnerability with the current API, I'll open a different PR  to handle this one.
=> Fix the deadlock in the destructor of RealtimePublisher

realtime_tools/CMakeLists.txt
Fixes recent breaking change in rolling
=> Use target_link_libraries instead of ament_target_dependencies

realtime_tools/CMakeLists.txt
Related to comment here: https://github.com/ros-controls/realtime_tools/pull/331#discussion_r2101051854
=> Use `Boost::boost` instead of ${Boost_LIBRARIES}

realtime_tools/include/realtime_tools/realtime_box.hpp, realtime_tools/include/realtime_tools/realtime_thread_safe_box.hpp
Change default mutex of `RealtimeThreadSafeBox` to use `realtime_tools::prio_inherit_mutex` on non-win systems and improve backwards compatibility by adding more aliasesto the old RealtimeBox class(es)
=> Change default mutex of `RealtimeThreadSafeBox` and add more aliases

realtime_tools/include/realtime_tools/realtime_publisher.hpp, realtime_tools/test/realtime_publisher_tests.cpp
Since #323 we get lots of deprecation warnings. Some could be silenced, but the constructor+destructor still complains.
@saikishor any idea to fix this? Do we really need the deprecation warning for the `msg_` member?
```
In file included from /workspaces/ros2_rolling_ws/src/realtime_tools/realtime_tools/test/realtime_publisher_tests.cpp:39:
/workspaces/ros2_rolling_ws/src/realtime_tools/realtime_tools/include/realtime_tools/realtime_publisher.hpp: In instantiation of ‘realtime_tools::RealtimePublisher<MessageT>::RealtimePublisher(PublisherSharedPtr) [with MessageT = test_msgs::msg::Strings_<std::allocator<void> >; PublisherSharedPtr = std::shared_ptr<rclcpp::Publisher<test_msgs::msg::Strings_<std::allocator<void> >, std::allocator<void> > >]’: …
```
=> Silence some warnings

realtime_tools/include/realtime_tools/realtime_thread_safe_box.hpp
Fixes:
```
ament_cppcheck...........................................................Failed
- hook id: ament_cppcheck
- exit code: 1
No problems found
No problems found
[realtime_tools/include/realtime_tools/realtime_thread_safe_box.hpp:227]: (error: missingReturn) Found a exit path from function with non-void return type that has missing return statement
1 errors
No problems found
No problems found
ament_cpplint............................................................Passed
```
=> Fix the failing ament_cppcheck in realtime_thread_safe_box

realtime_tools/CHANGELOG.rst
The trailing `_` is considered as a reference in RST and gives warnings during release process and building docs.
=> Fix rst syntax in changelog

realtime_tools/include/realtime_tools/realtime_publisher.hpp
I found a way in deprecating it without annoying deprecation warnings of the class itself.
Partially reverts #355 
Throws deprecation notices with current ros2_controller, but does not after
https://github.com/ros-controls/ros2_controllers/pull/1947
=> Deprecate `msg_` field
